version: '3.8'

services:
  hyperbooklm:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        UV_EXTRAS: "stt ocr web"
        INSTALL_OCR: "true"
        INSTALL_PLAYWRIGHT: "true"
        INSTALL_STT: "true"
    container_name: hyperbooklm
    ports:
      - "8080:8000"
    env_file:
      - .env.local
    restart: unless-stopped
    volumes:
      # Сохраняем базу ChromaDB между перезапусками контейнера
      - ./.chroma:/app/.chroma
